blank_issues_enabled: false
contact_links:
  - name: Read the contribution guide
    url: https://github.com/Api-Wrappers/awesome-api-wrappers/blob/main/CONTRIBUTING.md
    about: Before opening an issue, please review the contribution guidelines.
